### ISSUE TITLE
fix bug message

### ISSUE THREAD

**Issue by ccczg** [lixinyang123/CoreHome#29]
hey baby what`s up?

**Comment by lixinyang123** [comment]
换成 AES CBC 模式，初始化向量是随机的，导致无状态登录失效
[CBC 和 ECB 模式](https://www.cnblogs.com/wangle1001986/p/11468419.html)

**Comment by ccczg** [comment]
good idea ，Thank you Baby

**Comment by lixinyang123** [comment]
MDZZ

**Comment by lixinyang123** [comment]
修复了AES CBC 模式，随机初始化向量，导致无状态登录失效的BUG
32a093f
