### ISSUE TITLE
关于数据保存的问题

### ISSUE THREAD

**Issue by taka-10969** [lixinyang123/CoreHome#74]
作者您好，程序只有Blog板块的内容是存放在对应的MySQL数据库里的，其余的包括Profile,Theme等内容都找不到保存数据的文件，请问下这些内容是保存在哪里的，又如何还原它们，谢谢。

**Comment by lixinyang123** [comment]
数据库文件挂载在 './data/db' 中
主题包括个人信息在 './data' 中

**Comment by taka-10969** [comment]
这个data文件夹是存在阿里云oss上的吗，我本地没
有找到存储的数据

**Comment by lixinyang123** [comment]
您是使用 DockerHome 部署的，还是使用 CoreHome 编译运行的，开发环境和生产环境配置存储的位置不同

## 如果在开发环境下，配置文件目录如下
- Windows `C:/Server/CoreHome/data`
- Linux `/home/Server/CoreHome/data`

**Comment by taka-10969** [comment]
直接代码编译的

**Comment by lixinyang123** [comment]
根据你的系统，配置文件存储在不同的目录下

- Windows `C:/Server/CoreHome/data`
- Linux `/home/Server/CoreHome/data`

**Comment by taka-10969** [comment]
请问这个路径是写在那个配置文件里面？我能够自定义这个路径吗？

**Comment by lixinyang123** [comment]
如果使用 DockerHome 进行部署的时候可以通过配置文件修改文件挂载路径

否则需要在代码里修改存储路径

**Comment by taka-10969** [comment]
哈皮的，谢谢
